### PR TITLE
bootstrap script

### PR DESCRIPTION
**Pull request by daler**
This provides a way of cloning the repo into a new analysis directory.

The idea is that there's a whitelist (`manifest.txt`) of files in the repo that should be copied, anything not on the list is skipped.

```bash
git clone . tmpdir
cd tmpdir
git remote add upstream git@github.com:lcdb/lcdb-wf.git
git checkout -b newbranch
git rm $files-to-remove  # see below
git commit -m 'deleted stuff'
rsync tmpdir/ destdir/
```
Which files to delete from the temporary cloned repo: anything NOT matched by globs in `manifest.txt`, and  anything  that already exists in the destination dir.

### CODE REVIEW

**Comment by jfear** [comment]
Awesome, I was actually thinking about how to do this the other day!!

**Comment by daler** [comment]
I'd like to eventually do a

```bash
curl https://raw.githubusercontent.com/lcdb/lcdb-wf/master/bootstrap.py | python
```

**Comment by jfear** [comment]
Sorry, just trying to think things through. Can you describe your standard workflow/file tree to give me a better picture?

Each of my projects is a git repository. The question I am struggling with is how this fits in. I came up with the following:

1) bootstrap to a subfolder of my project repository
2) bootstrap to start a project folder

I am wondering how much communication you usually do with `upstream`. 

For (1), submodules would not really work because you end up removing `origin` and pointing to `upstream`. Here I think a subtree could work, but this makes pushing `upstream` challenging. 

For (2) you can just add a new `origin`, but would get complicated if you need to make new branches.  

Another option would be to use the github importer, but this would also break `upstream`. 

Perhaps I am missing something simple.

**Comment by daler** [comment]
hah, I was just writing these points in the readme! Though it's a bit complicated to explain.

When bootstrapping to an analysis directory *it's expected to not be a git repo yet*. In fact the script exits if it detects a `.git` dir in the destination.

I don't do much communicating with upstream (github), but a lot with origin (that is, wherever the cloned-from-github repo is living in my home directory). If I make a change in the analysis directory I want to be propagated back to origin, I actually use `meld analysis_dir origin_dir` to do the line-by-line changes to origin by hand. Then back in `origin` I make the commits and push to *its* origin, which is github.

Now all analysis directories that were cloned from the same origin can get the new changes. In practice I use `git merge master --no-ff --no-commit` in the analysis dir and then pick-and-choose which commits I want with `git cola`.

There's probably an easier or more straightforward way of doing this. The overall goal is that fixes and improvements in one analysis dir can be propagated out to all other analysis dirs.

**Pull request merged**
