### PR TITLE
add more docs and reorganize

### PR DESCRIPTION
**Pull request by mitraak**
Going through and adding some documentation and reorganizing some existing pages

### CODE REVIEW

**Comment by daler** [comment]
Awesome, thank you! Many fixes and improvements here.

Tests are failing for other reasons . . . once I work that out I'll merge this into v1.6rc

**Comment by mitraak** [comment]
Thanks! Planning to work more on the docs, especially figuring out how to reorganize the Rmd docs to fit with the rest of the page hierarchy and adding more docs especially for the gene patterns and functional enrichment pages. Hold off on the merge until then!

**Comment by daler** [comment]
The new content is great, thank you!

**Comment by daler** [comment]
There are some changes here that update the testing environment. I'm going to merge them into master so that we get passing tests on master as well as updated hosted docs.

**Pull request merged**
